#!/bin/bash

basedir="$(dirname $0)/.."

#add this flag to force config regeneration: --regenerate-configureapi
${basedir}/toolbox/swagger generate server \
  -f ${basedir}/spec/auth_service.yml \
  -A auth --main-package=. \
  -t ${basedir}/src \
  --principal "haw-hamburg.de/cloudWP/src.Session" \
  --server-package=api \
  --model-package=apimodel
