// Code generated by go-swagger; DO NOT EDIT.

// Package api Auth
//
//  User and Session Management API
//  Schemes:
//    http
//  Host: localhost:4000
//  BasePath: /auth
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package api
