// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"haw-hamburg.de/cloudWP/src/apimodel"
)

// GetUserByNameOKCode is the HTTP code returned for type GetUserByNameOK
const GetUserByNameOKCode int = 200

/*GetUserByNameOK successful operation

swagger:response getUserByNameOK
*/
type GetUserByNameOK struct {

	/*
	  In: Body
	*/
	Payload *apimodel.User `json:"body,omitempty"`
}

// NewGetUserByNameOK creates GetUserByNameOK with default headers values
func NewGetUserByNameOK() *GetUserByNameOK {

	return &GetUserByNameOK{}
}

// WithPayload adds the payload to the get user by name o k response
func (o *GetUserByNameOK) WithPayload(payload *apimodel.User) *GetUserByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user by name o k response
func (o *GetUserByNameOK) SetPayload(payload *apimodel.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middlewares deal with this
		}
	}
}
