// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*RegisterUserDefault successful operation

swagger:response registerUserDefault
*/
type RegisterUserDefault struct {
	_statusCode int
}

// NewRegisterUserDefault creates RegisterUserDefault with default headers values
func NewRegisterUserDefault(code int) *RegisterUserDefault {
	if code <= 0 {
		code = 500
	}

	return &RegisterUserDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the register user default response
func (o *RegisterUserDefault) WithStatusCode(code int) *RegisterUserDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the register user default response
func (o *RegisterUserDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *RegisterUserDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
