// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"haw-hamburg.de/cloudWP/src/apimodel"
)

// UserLoginOKCode is the HTTP code returned for type UserLoginOK
const UserLoginOKCode int = 200

/*UserLoginOK successful operation

swagger:response userLoginOK
*/
type UserLoginOK struct {
	/*date in UTC when token expires

	 */
	XExpiresAfter strfmt.DateTime `json:"X-Expires-After"`

	/*
	  In: Body
	*/
	Payload *apimodel.AccessTokenResponse `json:"body,omitempty"`
}

// NewUserLoginOK creates UserLoginOK with default headers values
func NewUserLoginOK() *UserLoginOK {

	return &UserLoginOK{}
}

// WithXExpiresAfter adds the xExpiresAfter to the user login o k response
func (o *UserLoginOK) WithXExpiresAfter(xExpiresAfter strfmt.DateTime) *UserLoginOK {
	o.XExpiresAfter = xExpiresAfter
	return o
}

// SetXExpiresAfter sets the xExpiresAfter to the user login o k response
func (o *UserLoginOK) SetXExpiresAfter(xExpiresAfter strfmt.DateTime) {
	o.XExpiresAfter = xExpiresAfter
}

// WithPayload adds the payload to the user login o k response
func (o *UserLoginOK) WithPayload(payload *apimodel.AccessTokenResponse) *UserLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user login o k response
func (o *UserLoginOK) SetPayload(payload *apimodel.AccessTokenResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Expires-After

	xExpiresAfter := o.XExpiresAfter.String()
	if xExpiresAfter != "" {
		rw.Header().Set("X-Expires-After", xExpiresAfter)
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserLoginBadRequestCode is the HTTP code returned for type UserLoginBadRequest
const UserLoginBadRequestCode int = 400

/*UserLoginBadRequest Invalid username/password supplied

swagger:response userLoginBadRequest
*/
type UserLoginBadRequest struct {
}

// NewUserLoginBadRequest creates UserLoginBadRequest with default headers values
func NewUserLoginBadRequest() *UserLoginBadRequest {

	return &UserLoginBadRequest{}
}

// WriteResponse to the client
func (o *UserLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
