// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"haw-hamburg.de/cloudWP/src/apimodel"
)

// UserInfoOKCode is the HTTP code returned for type UserInfoOK
const UserInfoOKCode int = 200

/*UserInfoOK successful operation

swagger:response userInfoOK
*/
type UserInfoOK struct {

	/*
	  In: Body
	*/
	Payload *apimodel.User `json:"body,omitempty"`
}

// NewUserInfoOK creates UserInfoOK with default headers values
func NewUserInfoOK() *UserInfoOK {

	return &UserInfoOK{}
}

// WithPayload adds the payload to the user info o k response
func (o *UserInfoOK) WithPayload(payload *apimodel.User) *UserInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user info o k response
func (o *UserInfoOK) SetPayload(payload *apimodel.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
